CREATE TABLE PRICES (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BRAND_ID INT NOT NULL,
    START_DATE TIMESTAMP NOT NULL,
    END_DATE TIMESTAMP NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL
);

CREATE INDEX idx_price_search ON PRICES (brand_id, product_id, start_date, end_date);
CREATE INDEX idx_price_priority ON PRICES (priority);
CREATE INDEX idx_price_dates ON PRICES (start_date, end_date);
